# main menu

############ Classes ############
[[main]]
    identifier = "classes"
    name       = "🧩 Fall Classes"
    url        = "/classes/"
    weight     = 1

[[main]]
    name       = "Ages 6-8: Lower Elementary Explorers"
    url        = "/classes/lower-elementary-explorers/"
    weight     = 1
    parent     = "classes"

[[main]]
    name       = "Ages 8-10: Upper Elementary Builders"
    url        = "/classes/upper-elementary-builders/"
    weight     = 2
    parent     = "classes"

[[main]]
    parent     = "classes"
    name       = "Ages 10-13: Middle School Innovators"
    url        = "/classes/middle-school-innovators/"
    weight     = 3

[[main]]
    parent     = "classes"
    name       = "Ages 14-18: High School Scholars"
    url        = "/classes/high-school-scholars/"
    weight     = 4

############ Camps ############

[[main]]
    name        = "⛺ One-Day Camps"
    url         = "/one-day-camps/"
    weight      = 2

############ Birthdays and Gaming ############
[[main]]
    identifier  = "fun"
    name        = "🎉 Parties & Gaming"
    # url         = "/fun/"
    weight      = 3
############ Birthdays ############
[[main]]
    name        = "🎂 Birthday Parties"
    url         = "/birthdays/"
    parent      = "fun"
    weight      = 1
############ Gaming ############
[[main]]
    name       = "🎮 Gaming Fridays"
    url        = "/gaming/"
    parent     = "fun"
    weight     = 2

############ Tutoring & Test Prep ############

[[main]]
    identifier = "academic-support"
    name       = "✏️ Tutoring & Test Prep"
    # url        = "/tutoring/"
    weight     = 4

[[main]]
    parent     = "academic-support"
    name       = "STEM Tutoring"
    url        = "/tutoring/"
    weight     = 1

[[main]]
    parent     = "academic-support"
    name       = "SAT & ACT Math Prep"
    url        = "/test-prep/sat-act-math/"
    weight     = 2

[[main]]
    parent     = "academic-support"
    name       = "AP Test Prep"
    url        = "/test-prep/ap/"
    weight     = 3

############ Homeschool ############
[[main]]
    name       = "🏠 Homeschool"
    url        = "/homeschool/"
    weight     = 5

############ Competitions ############
[[main]]
    name        = "🤖 WRO"
    url         = "/world-robot-olympiad/"
    weight      = 6









