# main menu
[[main]]
    name       = "Classes"
    url        = "/classes/"
    weight     = 2

# [[main]]
#     name       = "Kids and Teens"
#     url        = "/classes/"
#     weight     = 1
#     parent     = "Classes"

# [[main]]
#     parent     = "Classes"
#     name       = "Adults"
#     url        = "/adults/"
#     weight     = 2

# [[main]]
#     parent     = "Classes"
#     name       = "Certifications"
#     url        = "/certifications/"
#     weight     = 3


[[main]]
    name        = "Camps"
    url         = "/1-day-camps/"
    weight      = 3

# [[main]]
#     name        = "1-Day"
#     url         = "/1-day-camps/"
#     parent      = "Camps"
#     weight      = 1

# [[main]]
#     name        = "Summer"
#     url         = "/summer-camps/"
#     parent      = "Camps"
#     weight      = 4

# [[main]]
#     name        = "Winter Break"
#     url         = "/winter-break-camps/"
#     parent      = "Camps"
#     weight      = 2

# [[main]]
#     name        = "Spring Break"
#     url         = "/spring-break-camps/"
#     parent      = "Camps"
#     weight      = 3

[[main]]
    name       = "Gaming"
    url        = "/gaming/"
    weight     = 4

[[main]]
    name        = "Birthdays"
    url         = "/birthdays/"
    weight      = 5

[[main]]
    name       = "Tutoring"
    url        = "/tutoring/"
    weight     = 10

[[main]]
    name       = "Homeschoolers"
    url        = "/group-classes/"
    weight     = 11


[[main]]
    name        = "More"
    weight      = 12


[[main]]
    name        = "WRO"
    url         = "/wro"
    weight      = 3
    parent     = "More"

[[main]]
    name        = "Open House"
    url         = "/open-house/"
    weight      = 4
    parent     = "More"

[[main]]
    name       = "Team"
    url        = "/instructors/"
    weight     = 12
    parent     = "More"

[[main]]
    name       = "Contact"
    url        = "/contact/"
    weight     = 12
    parent     = "More"

[[main]]
    name       = "Login"
    url        = "#!/~/account"
    weight     = 13
    parent     = "More"