# main menu
[[main]]
    name       = "Classes"
    url        = "/classes/"
    weight     = 2

[[main]]
    name       = "Classes for Adults"
    url        = "/adults/"
    weight     = 1


[[main]]
    name        = "Camps"
    url         = "camps/"
    weight      = 3

[[main]]
    name        = "1-Day"
    url         = "1-day-camps/"
    parent      = "Camps"
    weight      = 1

# [[main]]
#     name        = "Winter Break"
#     url         = "winter-break-camps/"
#     parent      = "Camps"
#     weight      = 2

# [[main]]
#     name        = "Spring Break"
#     url         = "spring-break-camps/"
#     parent      = "Camps"
#     weight      = 3

[[main]]
    name        = "Summer"
    url         = "summer-camps/"
    parent      = "Camps"
    weight      = 5

[[main]]
    name        = "Birthday Parties"
    url         = "celebrations"
    weight      = 6

[[main]]
    name        = "WRO"
    url         = "wro"
    weight      = 7

[[main]]
    name        = "Events"
    weight      = 8


[[main]]
    name       = "Parents Night Out"
    url        = "/parents-night-out/"
    weight     = 2
    parent     = "Events"

[[main]]
    name       = "Minecraft Club"
    url        = "/minecraft/"
    weight     = 3
    parent     = "Events"

[[main]]
    name       = "Roblox Club"
    url        = "/roblox/"
    weight     = 4
    parent     = "Events"

[[main]]
    name       = "Fortnite Club"
    url        = "/fortnite/"
    weight     = 5
    parent     = "Events"

[[main]]
    name       = "Girl Powered Fridays"
    url        = "/girl-powered-fridays/"
    weight     = 9
    parent     = "Events"

# [[main]]
#     name       = "Chess Club"
#     url        = "/chess/"
#     weight     = 4
#     parent     = "Events"

[[main]]
    name       = "Tutoring"
    url        = "/tutoring/"
    weight     = 10

[[main]]
    name        = "About Us"
    hasChildren = true
    weight      = 11

[[main]]
    parent     = "About Us"
    name       = "Vision"
    url        = "/vision/"
    weight     = 1

[[main]]
    parent     = "About Us"
    name       = "Instructors"
    url        = "/instructors/"
    weight     = 2

[[main]]
    parent     = "About Us"
    name       = "Scholarships"
    url        = "/scholarships/"
    weight     = 3


[[main]]
    parent     = "About Us"
    name       = "Terms and Conditions"
    url        = "/terms/"
    weight     = 4

[[main]]
    parent     = "About Us"
    name       = "Privacy Policy"
    url        = "/privacy-policy/"
    weight     = 5

[[main]]
    parent     = "About Us"
    name       = "Refund Policy"
    url        = "/refund-policy/"
    weight     = 6


[[main]]
    name       = "Contact"
    url        = "/contact/"
    weight     = 12

[[main]]
    name       = "Login"
    url        = "#!/~/account"
    weight     = 13