math=true

ecwid_store_id = 107344503

#################### default parameters ################################
# favicon
favicon = "images/brand/blue-ridge-highlands-cropped.png"
# logo
logo = "images/brand/blue-ridge-highlands-cropped.png"
logo_darkmode = "#"
# use `px` or `x` with logo_width = " example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "80px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Blue Ridge Boost"
# theme-mode
theme_switcher = false
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = []
# contact form action
contact_form_action = "https://formspree.io/f/myyawwzg" 
# contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "G-JV87PS188M" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""
# copyright
theme_copyright = true
copyright = "Copyright by Blue Ridge Boost"

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format. example - "images/preloader.gif"

# Navigation button
[navigation_button]
enable = false
label = "Get a Demo"
link = "get-demo/"

# Crisp Chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Charlottesville coding for kids", 
        "Charlottesville Python classes", 
        "Charlottesville robotics", 
        "cvillecoding", "coding", "summer camps"]
description = "Computer coding, robotics, math, and chess"
author = "Blue Ridge Boost"
image = "images/brand/blue-ridge-highlands-cropped.png"                           
# this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = ""  # your username

# site verifications
[site_verification]
google = "GT-TXZCPHS"   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://facebook.com/blueridgeboost"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://x.com/blueridgeboost"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/blueridgeboost"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.linkedin.com/company/blue-ridge-boost/"

[ecwid_ids]
chess-2024-10-10="701743571"
chess-2024-10-17="701743332"
chess-2024-11-07="701742596"
chess-2024-11-14="701741889"
chess-2024-11-21="701741467"
chess-2024-12-04="701741468"
chess-2024-12-11="701743333"
chess-2025-01-09="701742597"
chess-2025-01-16="701741470"
chess-2025-01-23="701741471"
chess-2025-01-30="701743572"
chess-2025-02-06="701742598"
chess-2025-02-13="701742599"
chess-2025-02-20="701741654"
chess-2025-02-27="701741473"
chess-2025-03-06="701741655"
chess-2025-03-20="701741890"
chess-2025-04-10="701741474"
chess-2025-04-17="701742601"
chess-2025-04-24="701743335"
Advanced-C-Plus-Plus="701741900"
Advanced-JavaScript="701741481"
Advanced-Problem-Solving="701742606"
Aerial-Drones="701743341"
Aerial-Drones-2="701742607"
Algebra-Excellence="701742608"
Banana-Code-Quest="701741482"
Banana-Tales="701742609"
Code-Explorers="701743342"
First-Lego-League-VEX-IQ="701741903"
First-Tech-Challenge="701741904"
Girl-Powered-First-Tech-Challenge="701741663"
Girl-Powered-TechQuest="701741664"
Girl-Powered-VEX-IQ-Robotics-Explorers="701743578"
Girl-Powered-Drone-Squad="701743579"
Intro-to-AMC10="701743343"
Java-for-APCS="701742613"
Junior-Robotics-Adventures="701741486"
Junior-Robotics-Adventures-on-Saturday="701741487"
Kids-Coding-Course="701743344"
Math-Boost-5-6="701741488"
Math-Boost-1-2="701743345"
Math-Boost-3-4="701741908"
Math-Excellence-1-2="701741909"
Math-Excellence-3-4="701741910"
Math-Hoppers="701742614"
Math-Leapers="701741911"
Prealgebra-Mastery="701742615"
Math-Mastery-1-2="701743346"
Math-Mastery-3-4="701741489"
Mobile-App-Development="701741667"
Prealgebra-Excellence="701742616"
Problem-Solving="701743582"
Python-Fundamentals="701741490"
Python-Wizardry="701742618"
Robotics-Discovery-1-2="701743348"
Robotics-Discovery-2-3="701741912"
Robotics-Discovery-4-5="701741668"
Robotics-Explorations="701743583"
Sphero-Time-Travelers="701741669"
TechQuest="701741670"
Vex-IQ-Rapid-Relay="701741671"
Video-Game-Design="701743349"
gpf-2024-10-11="701741896"
gpf-2024-11-01="701741476"
gpf-2024-11-15="701741897"
gpf-2024-12-06="701741657"
gpf-2025-01-10="701741477"
gpf-2025-01-24="701741658"
gpf-2025-02-07="701742605"
gpf-2025-02-21="701741478"
gpf-2025-03-07="701741660"
gpf-2025-03-21="701741898"
gpf-2025-04-25="701743339"
gpf-2025-05-02="701741479"
gpf-2025-05-16="701743340"
Algebra-Mastery="701743576"
Algebra-Practice="701741902"
Calculus-AB-Mastery="701741662"
Calculus-AB-Practice="701741484"
Geometry-Practice="701742610"
Integrated-Math-1-Mastery="701741905"
Integrated-Math-1-Practice="701741906"
Integrated-Math-2-Mastery="701742611"
Integrated-Math-2-Practice="701741907"
Integrated-Math-3-Mastery="701741485"
Integrated-Math-3-Practice="701742612"
Precalculus-Practice="701742617"
Statistics-Mastery="701741913"
Statistics-Practice="701741914"
one-day-2025-04-18="701743323"
one-day-2025-04-28="701741458"
one-day-2024-12-23="701742588"
one-day-2024-12-24="701742589"
one-day-2024-12-26="701742590"
one-day-2024-12-27="701743324"
one-day-2024-12-28="701743325"
one-day-2024-12-29="701741460"
one-day-2024-12-30="701741461"
one-day-2024-12-31="701743564"
one-day-2024-12-06="701741649"
one-day-2025-02-14="701741877"
one-day-2025-02-17="701741879"
one-day-2025-02-07="701741880"
one-day-2025-01-17="701743326"
one-day-2025-01-20="701741650"
one-day-2025-01-21="701743565"
one-day-2025-01-06="701741463"
one-day-2025-01-07="701743327"
one-day-2025-03-17="701741883"
one-day-2025-03-18="701743328"
one-day-2025-03-21="701741884"
one-day-2025-03-26="701741885"
one-day-2025-03-27="701743566"
one-day-2025-03-28="701743329"
one-day-2025-03-31="701741464"
one-day-2024-11-01="701742594"
one-day-2024-11-15="701741465"
one-day-2024-11-04="701743567"
one-day-2024-11-05="701743568"
one-day-2024-10-11="701741651"
one-day-2024-10-14="701741886"
one-day-2024-10-15="701743569"
one-day-2024-10-18="701741887"
one-day-2024-10-24="701741653"
one-day-2024-10-25="701743570"
one-day-2024-10-30="701743331"
one-day-2024-10-31="701742595"
one-day-2024-09-27="701741466"
pno-2024-10-04="701741891"
pno-2024-10-18="701743574"
pno-2024-11-08="701742602"
pno-2024-12-13="701743575"
pno-2025-01-31="701743337"
pno-2025-02-28="701741892"
pno-2025-03-14="701741894"
pno-2025-04-13="701743338"
pno-2025-05-09="701742603"



[inventory]
chess-2024-10-10="3"
chess-2024-10-17="6"
chess-2024-11-07="12"
chess-2024-11-14="9"
chess-2024-11-21="11"
chess-2024-12-04="12"
chess-2024-12-11="12"
chess-2025-01-09="10"
chess-2025-01-16="12"
chess-2025-01-23="12"
chess-2025-01-30="12"
chess-2025-02-06="12"
chess-2025-02-13="12"
chess-2025-02-20="12"
chess-2025-02-27="12"
chess-2025-03-06="12"
chess-2025-03-20="10"
chess-2025-04-10="12"
chess-2025-04-17="10"
chess-2025-04-24="12"
Advanced-C-Plus-Plus="6"
Advanced-JavaScript="6"
Advanced-Problem-Solving="4"
Aerial-Drones="0"
Aerial-Drones-2="4"
Algebra-Excellence="6"
Banana-Code-Quest="4"
Banana-Tales="5"
Code-Explorers="6"
First-Lego-League-VEX-IQ="0"
First-Tech-Challenge="0"
Girl-Powered-First-Tech-Challenge="8"
Girl-Powered-TechQuest="6"
Girl-Powered-VEX-IQ-Robotics-Explorers="6"
Girl-Powered-Drone-Squad="0"
Intro-to-AMC10="4"
Java-for-APCS="6"
Junior-Robotics-Adventures="5"
Junior-Robotics-Adventures-on-Saturday="5"
Kids-Coding-Course="5"
Math-Boost-5-6="6"
Math-Boost-1-2="6"
Math-Boost-3-4="5"
Math-Excellence-1-2="0"
Math-Excellence-3-4="4"
Math-Hoppers="6"
Math-Leapers="4"
Prealgebra-Mastery="5"
Math-Mastery-1-2="5"
Math-Mastery-3-4="3"
Mobile-App-Development="6"
Prealgebra-Excellence="4"
Problem-Solving="4"
Python-Fundamentals="3"
Python-Wizardry="6"
Robotics-Discovery-1-2="5"
Robotics-Discovery-2-3="3"
Robotics-Discovery-4-5="1"
Robotics-Explorations="6"
Sphero-Time-Travelers="6"
TechQuest="4"
Vex-IQ-Rapid-Relay="5"
Video-Game-Design="4"
gpf-2024-10-11="11"
gpf-2024-11-01="0"
gpf-2024-11-15="4"
gpf-2024-12-06="11"
gpf-2025-01-10="2"
gpf-2025-01-24="9"
gpf-2025-02-07="11"
gpf-2025-02-21="4"
gpf-2025-03-07="10"
gpf-2025-03-21="11"
gpf-2025-04-25="11"
gpf-2025-05-02="10"
gpf-2025-05-16="11"
Algebra-Mastery=[["Oct 16, 23, 30; Nov 6",6],["Nov 13, 20; Dec 4, 11",6]]
Algebra-Practice=[["Oct 14, 21, 28; Nov 4",4],["Nov 11, 18; Dec 2, 9",4]]
Calculus-AB-Mastery=[["Oct 20, 27; Nov 3, 10",6],["Nov 17, 24; Dec 8, 15",6]]
Calculus-AB-Practice=[["Oct 16, 23, 30; Nov 6",4],["Nov 13, 20; Dec 4, 11",4]]
Geometry-Practice=[["Oct 14, 21, 28; Nov 4",4],["Nov 11, 18; Dec 2, 9",4]]
Integrated-Math-1-Mastery=[["Oct 19, 26; Nov 2, 9",4],["Nov 16, 23; Dec 7, 14",4]]
Integrated-Math-1-Practice=[["Oct 14, 21, 28; Nov 4",4],["Nov 11, 18; Dec 2, 9",4]]
Integrated-Math-2-Mastery=[["Oct 19, 26; Nov 2, 9",4],["Nov 16, 23; Dec 7, 14",4]]
Integrated-Math-2-Practice=[["Oct 14, 21, 28; Nov 4",4],["Nov 11, 18; Dec 2, 9",4]]
Integrated-Math-3-Mastery=[["Oct 19, 26; Nov 2, 9",4],["Nov 16, 23; Dec 7, 14",4]]
Integrated-Math-3-Practice=[["Oct 15, 22, 29; Nov 5",4],["Nov 12, 19; Dec 3, 10",4]]
Precalculus-Practice=[["Oct 15, 22, 29; Nov 5",4],["Nov 12, 19; Dec 3, 10",4]]
Statistics-Mastery=[["Oct 20, 27; Nov 3, 10",4],["Nov 17, 24; Dec 8, 15",4]]
Statistics-Practice=[["Oct 16, 23, 30; Nov 6",4],["Nov 13, 20; Dec 4, 11",4]]
one-day-2025-04-18="16"
one-day-2025-04-28="13"
one-day-2024-12-23="15"
one-day-2024-12-24="15"
one-day-2024-12-26="15"
one-day-2024-12-27="15"
one-day-2024-12-28="16"
one-day-2024-12-29="16"
one-day-2024-12-30="15"
one-day-2024-12-31="15"
one-day-2024-12-06="16"
one-day-2025-02-14="16"
one-day-2025-02-17="16"
one-day-2025-02-07="15"
one-day-2025-01-17="16"
one-day-2025-01-20="14"
one-day-2025-01-21="16"
one-day-2025-01-06="15"
one-day-2025-01-07="16"
one-day-2025-03-17="15"
one-day-2025-03-18="16"
one-day-2025-03-21="15"
one-day-2025-03-26="16"
one-day-2025-03-27="16"
one-day-2025-03-28="16"
one-day-2025-03-31="16"
one-day-2024-11-01="16"
one-day-2024-11-15="16"
one-day-2024-11-04="10"
one-day-2024-11-05="12"
one-day-2024-10-11="16"
one-day-2024-10-14="13"
one-day-2024-10-15="13"
one-day-2024-10-18="14"
one-day-2024-10-24="10"
one-day-2024-10-25="14"
one-day-2024-10-30="15"
one-day-2024-10-31="16"
one-day-2024-09-27="14"
pno-2024-10-04="1"
pno-2024-10-18="10"
pno-2024-11-08="10"
pno-2024-12-13="10"
pno-2025-01-31="10"
pno-2025-02-28="10"
pno-2025-03-14="10"
pno-2025-04-13="10"
pno-2025-05-09="10"
[prices]
Algebra-Mastery="155"
Algebra-Practice="155"
Calculus-AB-Mastery="175"
Calculus-AB-Practice="175"
Geometry-Practice="155"
Integrated-Math-1-Mastery="155"
Integrated-Math-1-Practice="155"
Integrated-Math-2-Mastery="155"
Integrated-Math-2-Practice="155"
Integrated-Math-3-Mastery="155"
Integrated-Math-3-Practice="155"
Precalculus-Practice="155"
Statistics-Mastery="175"
Statistics-Practice="175"
Advanced-C-Plus-Plus="179"
Advanced-JavaScript="129"
Advanced-Problem-Solving="235"
Aerial-Drones="235"
Aerial-Drones-2="235"
Algebra-Excellence="195"
Banana-Code-Quest="129"
Banana-Tales="129"
Code-Explorers="129"
First-Lego-League-VEX-IQ="195"
First-Tech-Challenge="195"
Girl-Powered-First-Tech-Challenge="0"
Girl-Powered-TechQuest="155"
Girl-Powered-VEX-IQ-Robotics-Explorers="195"
Girl-Powered-Drone-Squad="235"
Intro-to-AMC10="235"
Java-for-APCS="179"
Junior-Robotics-Adventures="129"
Junior-Robotics-Adventures-on-Saturday="129"
Kids-Coding-Course="129"
Math-Boost-5-6="155"
Math-Boost-1-2="129"
Math-Boost-3-4="129"
Math-Excellence-1-2="129"
Math-Excellence-3-4="129"
Math-Hoppers="155"
Math-Leapers="155"
Prealgebra-Mastery="179"
Math-Mastery-1-2="129"
Math-Mastery-3-4="129"
Mobile-App-Development="179"
Prealgebra-Excellence="195"
Problem-Solving="195"
Python-Fundamentals="129"
Python-Wizardry="179"
Robotics-Discovery-1-2="129"
Robotics-Discovery-2-3="129"
Robotics-Discovery-4-5="129"
Robotics-Explorations="129"
Sphero-Time-Travelers="129"
TechQuest="155"
Vex-IQ-Rapid-Relay="195"
Video-Game-Design="179"



[ecwid_categories]
chess-2024-10-10="Chess Club"
chess-2024-10-17="Chess Club"
chess-2024-11-07="Chess Club"
chess-2024-11-14="Chess Club"
chess-2024-11-21="Chess Club"
chess-2024-12-04="Chess Club"
chess-2024-12-11="Chess Club"
chess-2025-01-09="Chess Club"
chess-2025-01-16="Chess Club"
chess-2025-01-23="Chess Club"
chess-2025-01-30="Chess Club"
chess-2025-02-06="Chess Club"
chess-2025-02-13="Chess Club"
chess-2025-02-20="Chess Club"
chess-2025-02-27="Chess Club"
chess-2025-03-06="Chess Club"
chess-2025-03-20="Chess Club"
chess-2025-04-10="Chess Club"
chess-2025-04-17="Chess Club"
chess-2025-04-24="Chess Club"
Advanced-C-Plus-Plus="Subscription Classes"
Advanced-JavaScript="Subscription Classes"
Advanced-Problem-Solving="Subscription Classes"
Aerial-Drones="Subscription Classes"
Aerial-Drones-2="Subscription Classes"
Algebra-Excellence="Subscription Classes"
Banana-Code-Quest="Subscription Classes"
Banana-Tales="Subscription Classes"
Code-Explorers="Subscription Classes"
First-Lego-League-VEX-IQ="Subscription Classes"
First-Tech-Challenge="Subscription Classes"
Girl-Powered-First-Tech-Challenge="Subscription Classes"
Girl-Powered-TechQuest="Subscription Classes"
Girl-Powered-VEX-IQ-Robotics-Explorers="Subscription Classes"
Girl-Powered-Drone-Squad="Subscription Classes"
Intro-to-AMC10="Subscription Classes"
Java-for-APCS="Subscription Classes"
Junior-Robotics-Adventures="Subscription Classes"
Junior-Robotics-Adventures-on-Saturday="Subscription Classes"
Kids-Coding-Course="Subscription Classes"
Math-Boost-5-6="Subscription Classes"
Math-Boost-1-2="Subscription Classes"
Math-Boost-3-4="Subscription Classes"
Math-Excellence-1-2="Subscription Classes"
Math-Excellence-3-4="Subscription Classes"
Math-Hoppers="Subscription Classes"
Math-Leapers="Subscription Classes"
Prealgebra-Mastery="Subscription Classes"
Math-Mastery-1-2="Subscription Classes"
Math-Mastery-3-4="Subscription Classes"
Mobile-App-Development="Subscription Classes"
Prealgebra-Excellence="Subscription Classes"
Problem-Solving="Subscription Classes"
Python-Fundamentals="Subscription Classes"
Python-Wizardry="Subscription Classes"
Robotics-Discovery-1-2="Subscription Classes"
Robotics-Discovery-2-3="Subscription Classes"
Robotics-Discovery-4-5="Subscription Classes"
Robotics-Explorations="Subscription Classes"
Sphero-Time-Travelers="Subscription Classes"
TechQuest="Subscription Classes"
Vex-IQ-Rapid-Relay="Subscription Classes"
Video-Game-Design="Subscription Classes"
gpf-2024-10-11="Girl Powered Fridays"
gpf-2024-11-01="Girl Powered Fridays"
gpf-2024-11-15="Girl Powered Fridays"
gpf-2024-12-06="Girl Powered Fridays"
gpf-2025-01-10="Girl Powered Fridays"
gpf-2025-01-24="Girl Powered Fridays"
gpf-2025-02-07="Girl Powered Fridays"
gpf-2025-02-21="Girl Powered Fridays"
gpf-2025-03-07="Girl Powered Fridays"
gpf-2025-03-21="Girl Powered Fridays"
gpf-2025-04-25="Girl Powered Fridays"
gpf-2025-05-02="Girl Powered Fridays"
gpf-2025-05-16="Girl Powered Fridays"
Algebra-Mastery="Session Classes"
Algebra-Practice="Session Classes"
Calculus-AB-Mastery="Session Classes"
Calculus-AB-Practice="Session Classes"
Geometry-Practice="Session Classes"
Integrated-Math-1-Mastery="Session Classes"
Integrated-Math-1-Practice="Session Classes"
Integrated-Math-2-Mastery="Session Classes"
Integrated-Math-2-Practice="Session Classes"
Integrated-Math-3-Mastery="Session Classes"
Integrated-Math-3-Practice="Session Classes"
Precalculus-Practice="Session Classes"
Statistics-Mastery="Session Classes"
Statistics-Practice="Session Classes"
one-day-2025-04-18="1-Day Camps"
one-day-2025-04-28="1-Day Camps"
one-day-2024-12-23="1-Day Camps"
one-day-2024-12-24="1-Day Camps"
one-day-2024-12-26="1-Day Camps"
one-day-2024-12-27="1-Day Camps"
one-day-2024-12-28="1-Day Camps"
one-day-2024-12-29="1-Day Camps"
one-day-2024-12-30="1-Day Camps"
one-day-2024-12-31="1-Day Camps"
one-day-2024-12-06="1-Day Camps"
one-day-2025-02-14="1-Day Camps"
one-day-2025-02-17="1-Day Camps"
one-day-2025-02-07="1-Day Camps"
one-day-2025-01-17="1-Day Camps"
one-day-2025-01-20="1-Day Camps"
one-day-2025-01-21="1-Day Camps"
one-day-2025-01-06="1-Day Camps"
one-day-2025-01-07="1-Day Camps"
one-day-2025-03-17="1-Day Camps"
one-day-2025-03-18="1-Day Camps"
one-day-2025-03-21="1-Day Camps"
one-day-2025-03-26="1-Day Camps"
one-day-2025-03-27="1-Day Camps"
one-day-2025-03-28="1-Day Camps"
one-day-2025-03-31="1-Day Camps"
one-day-2024-11-01="1-Day Camps"
one-day-2024-11-15="1-Day Camps"
one-day-2024-11-04="1-Day Camps"
one-day-2024-11-05="1-Day Camps"
one-day-2024-10-11="1-Day Camps"
one-day-2024-10-14="1-Day Camps"
one-day-2024-10-15="1-Day Camps"
one-day-2024-10-18="1-Day Camps"
one-day-2024-10-24="1-Day Camps"
one-day-2024-10-25="1-Day Camps"
one-day-2024-10-30="1-Day Camps"
one-day-2024-10-31="1-Day Camps"
one-day-2024-09-27="1-Day Camps"
pno-2024-10-04="Parents' Night Out"
pno-2024-10-18="Parents' Night Out"
pno-2024-11-08="Parents' Night Out"
pno-2024-12-13="Parents' Night Out"
pno-2025-01-31="Parents' Night Out"
pno-2025-02-28="Parents' Night Out"
pno-2025-03-14="Parents' Night Out"
pno-2025-04-13="Parents' Night Out"
pno-2025-05-09="Parents' Night Out"